GIT_TOKEN = "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"
GIT_PUBLIC_REPO = "OdrAAdeKK/coronamax-public"
GIT_PUBLIC_BRANCH = "main"
GIT_PUBLIC_PATH = "data"
GIT_AUTHOR_NAME = "CoronaMax Publisher"
GIT_AUTHOR_EMAIL = "odradek78@free.fr"
